import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { propsToType } from "../can-i-email/maps/props-to-type";
import { computeSupportCoverage } from "../can-i-email/compute-support-coverage";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAPS_DIR = path.resolve(__dirname, "../style-props/can-i-email/maps");

interface CanIEmailItem {
  slug: string;
  category: string;
  title: string;
  description: string;
  url: string;
  last_test_date: string;
  stats: Record<string, Record<string, Record<string, string>>>;
  notes_by_num: Record<string, string> | null;
  notes: string | null;
}

interface Coverage {
  support: number;
  partial: number;
  notSupported: number;
}

interface ProcessedItem {
  slug: string;
  description: string;
  url: string;
  last_test_date: string;
  coverage: Coverage;
  notes: string | null;
  type: string;
}

function extractNeededFields(item: CanIEmailItem, propName: string): ProcessedItem {
  const type = (propsToType as any)[propName] || "string";
  return {
    slug: item.slug,
    description: item.description,
    url: item.url,
    last_test_date: item.last_test_date,
    coverage: computeSupportCoverage(item.stats),
    notes: item.notes,
    type,
  };
}

async function run() {
  console.log("Fetching data from caniemail.com...");
  const response = await fetch("https://www.caniemail.com/api/data.json");
  const json = (await response.json()) as { data: CanIEmailItem[] };

  const cssItems = json.data.filter((item) => item.category === "css");

  const cssUnits: Record<string, ProcessedItem> = {};
  const cssFunctions: Record<string, ProcessedItem> = {};
  const cssAtRules: Record<string, ProcessedItem> = {};
  const cssValues: Record<string, ProcessedItem> = {};
  const cssProps: Record<string, ProcessedItem> = {};

  for (const item of cssItems) {
    const title = item.title;

    // Skip keys containing spaces
    if (title.includes(" ")) {
      if (!title.includes("&")) {
        continue;
      }
    }

    if (item.slug.startsWith("css-unit-")) {
      cssUnits[title] = extractNeededFields(item, title);
    } else if (
      item.slug.startsWith("css-function-") ||
      item.slug === "css-linear-gradient" ||
      title.endsWith("()")
    ) {
      cssFunctions[title] = extractNeededFields(item, title);
    } else if (title.startsWith("@")) {
      cssAtRules[title] = extractNeededFields(item, title);
    } else if (title.includes(":")) {
      cssValues[title] = extractNeededFields(item, title);
    } else if (title.includes("&")) {
      const parts = title.split("&").map((s) => s.trim());
      for (const part of parts) {
        if (!part.includes(" ")) {
          cssProps[part] = extractNeededFields(item, part);
        }
      }
    } else {
      cssProps[title] = extractNeededFields(item, title);
    }
  }

  // Create directory if it doesn't exist
  await fs.mkdir(MAPS_DIR, { recursive: true });

  const files = {
    "properties.ts": { name: "canIEmailCSSProperties", data: cssProps },
    "units.ts": { name: "canIEmailCSSUnits", data: cssUnits },
    "functions.ts": { name: "canIEmailCSSFunctions", data: cssFunctions },
    "at-rules.ts": { name: "canIEmailCSSAtRules", data: cssAtRules },
    "values.ts": { name: "canIEmailCSSValues", data: cssValues },
  };

  for (const [filename, { name, data }] of Object.entries(files)) {
    const filePath = path.join(MAPS_DIR, filename);
    const content = `// This file is auto-generated by src/scripts/can-i-email.ts
// Do not edit this file manually.

export const ${name} = ${JSON.stringify(data, null, 2)} as const;
`;
    await fs.writeFile(filePath, content, "utf8");
    console.log(`Saved ${filename} to ${MAPS_DIR}`);
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
