import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const MAPS_DIR = path.resolve(__dirname, '../style-props/can-i-email/maps')

function extractNeededFields(item) {
  return {
    slug: item.slug,
    description: item.description,
    url: item.url,
    last_test_date: item.last_test_date,
    stats: item.stats,
    notes_by_num: item.notes_by_num,
    notes: item.notes,
  }
}

async function run() {
  console.log('Fetching data from caniemail.com...')
  const response = await fetch('https://www.caniemail.com/api/data.json')
  const json = await response.json()

  const cssItems = json.data.filter(item => item.category === 'css')

  const cssUnits = {}
  const cssFunctions = {}
  const cssAtRules = {}
  const cssValues = {}
  const cssProps = {}

  for (const item of cssItems) {
    const title = item.title
    const extracted = extractNeededFields(item)

    if (item.slug.startsWith('css-unit-')) {
      cssUnits[title] = extracted
    } else if (item.slug.startsWith('css-function-')) {
      cssFunctions[title] = extracted
    } else if (title.startsWith('@')) {
      cssAtRules[title] = extracted
    } else if (title.includes(':')) {
      cssValues[title] = extracted
    } else if (title.includes('&')) {
      const parts = title.split('&').map(s => s.trim())
      for (const part of parts) {
        cssProps[part] = extracted
      }
    } else {
      cssProps[title] = extracted
    }
  }

  // Create directory if it doesn't exist
  await fs.mkdir(MAPS_DIR, { recursive: true })

  const files = {
    'properties.ts': { name: 'canIEmailCSSProperties', data: cssProps },
    'units.ts': { name: 'canIEmailCSSUnits', data: cssUnits },
    'functions.ts': { name: 'canIEmailCSSFunctions', data: cssFunctions },
    'at-rules.ts': { name: 'canIEmailCSSAtRules', data: cssAtRules },
    'values.ts': { name: 'canIEmailCSSValues', data: cssValues },
  }

  for (const [filename, { name, data }] of Object.entries(files)) {
    const filePath = path.join(MAPS_DIR, filename)
    const content = `// This file is auto-generated by src/scripts/can-i-email.js
// Do not edit this file manually.

export const ${name} = ${JSON.stringify(data, null, 2)} as const;
`
    await fs.writeFile(filePath, content, 'utf8')
    console.log(`Saved ${filename} to ${MAPS_DIR}`)
  }
}

run().catch(err => {
  console.error(err)
  process.exit(1)
})
