import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { canIEmailCSSProperties } from "../can-i-email/__generated_maps__/properties";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = path.resolve(__dirname, "../types/style-props/index.ts");

const SUPPORT_THRESHOLD = 40;

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

async function run() {
  console.log("Generating system types with JSDoc...");

  const properties = Object.entries(canIEmailCSSProperties);

  const lines = [
    "// This file is auto-generated by src/scripts/generate-types.ts",
    "// Do not edit this file manually.",
    "",
    'import type { Config } from "../config";',
    'import type { AnyString, PropertyValue } from "./types";',
    "",
    'export * from "./types";',
    "",
    "export interface SystemProperties<T = Config> {",
  ];

  for (const [name, data] of properties) {
    const camelName = toCamelCase(name);
    const { slug, description, url, last_test_date, coverage, notes, type } = data;

    lines.push("  /**");
    if (description) {
      lines.push(`   * ${description}`);
    }
    if (url) {
      lines.push(`   * @see ${url}`);
    }
    if (slug) {
      lines.push(`   * @slug ${slug}`);
    }
    if (last_test_date) {
      lines.push(`   * @last_test_date ${last_test_date}`);
    }

    lines.push(`   * @support ${coverage.support.toFixed(2)}%`);
    lines.push(`   * @partial ${coverage.partial.toFixed(2)}%`);
    lines.push(`   * @not_supported ${coverage.notSupported.toFixed(2)}%`);

    if (notes) {
      lines.push(`   * @notes ${notes}`);
    }

    if (coverage.support < SUPPORT_THRESHOLD) {
      lines.push(
        "   * @deprecated poor support coverage. This property might not work as expected in many email clients.",
      );
    }

    lines.push("   */");

    if (type === "string") {
      lines.push(`  ${camelName}?: AnyString;`);
    } else {
      lines.push(`  ${camelName}?: PropertyValue<T, "${type}">;`);
    }
  }

  lines.push("}");
  lines.push("");

  await fs.writeFile(OUTPUT_FILE, lines.join("\n"), "utf8");
  console.log(`Generated ${OUTPUT_FILE}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
