// This file is auto-generated by src/scripts/generate-types.ts
// Do not edit this file manually.

import type { Config } from "../config";
import type { AnyString, PropertyValue } from "./types";

export * from "./types";

export interface SystemProperties<T = Config> {
  /**
   * @see https://www.caniemail.com/features/css-accent-color/
   * @slug css-accent-color
   * @last_test_date 2023-12-19
   * @support 15.22%
   * @partial 0.00%
   * @not_supported 84.78%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  accentColor?: PropertyValue<T, "colors">;
  /**
   * @see https://www.caniemail.com/features/css-align-items/
   * @slug css-align-items
   * @last_test_date 2023-12-19
   * @support 61.11%
   * @partial 0.00%
   * @not_supported 38.89%
   */
  alignItems?: AnyString;
  /**
   * Tests for the shorthand `animation` property and its longhand equivalents.
   * @see https://www.caniemail.com/features/css-animation/
   * @slug css-animation
   * @last_test_date 2023-12-19
   * @support 27.08%
   * @partial 6.25%
   * @not_supported 66.67%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  animation?: AnyString;
  /**
   * Sets a preferred aspect ratio for the element
   * @see https://www.caniemail.com/features/css-aspect-ratio/
   * @slug css-aspect-ratio
   * @last_test_date 2023-12-19
   * @support 32.69%
   * @partial 0.00%
   * @not_supported 67.31%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  aspectRatio?: AnyString;
  /**
   * Lets you apply graphical effects such as blurring or color shifting to the area behind an element.
   * @see https://www.caniemail.com/features/css-backdrop-filter/
   * @slug css-backdrop-filter
   * @last_test_date 2024-01-17
   * @support 37.84%
   * @partial 0.00%
   * @not_supported 62.16%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  backdropFilter?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-blend-mode/
   * @slug css-background-blend-mode
   * @last_test_date 2019-02-28
   * @support 58.82%
   * @partial 3.92%
   * @not_supported 37.25%
   */
  backgroundBlendMode?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-clip/
   * @slug css-background-clip
   * @last_test_date 2019-02-28
   * @support 58.82%
   * @partial 3.92%
   * @not_supported 37.25%
   */
  backgroundClip?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-color/
   * @slug css-background-color
   * @last_test_date 2019-02-28
   * @support 90.20%
   * @partial 9.80%
   * @not_supported 0.00%
   */
  backgroundColor?: PropertyValue<T, "colors">;
  /**
   * @see https://www.caniemail.com/features/css-background-image/
   * @slug css-background-image
   * @last_test_date 2023-07-24
   * @support 60.00%
   * @partial 27.69%
   * @not_supported 12.31%
   */
  backgroundImage?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-origin/
   * @slug css-background-origin
   * @last_test_date 2019-02-28
   * @support 58.82%
   * @partial 3.92%
   * @not_supported 37.25%
   */
  backgroundOrigin?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-position/
   * @slug css-background-position
   * @last_test_date 2019-02-28
   * @support 81.13%
   * @partial 7.55%
   * @not_supported 11.32%
   */
  backgroundPosition?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-repeat/
   * @slug css-background-repeat
   * @last_test_date 2019-02-28
   * @support 81.13%
   * @partial 7.55%
   * @not_supported 11.32%
   */
  backgroundRepeat?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background-size/
   * @slug css-background-size
   * @last_test_date 2019-02-28
   * @support 72.00%
   * @partial 4.00%
   * @not_supported 24.00%
   */
  backgroundSize?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-background/
   * @slug css-background
   * @last_test_date 2023-07-24
   * @support 57.63%
   * @partial 40.68%
   * @not_supported 1.69%
   */
  background?: PropertyValue<T, "colors">;
  /**
   * Defines the horizontal or vertical size of an element's block, depending on its writing mode.
   * @see https://www.caniemail.com/features/css-block-inline-size/
   * @slug css-block-inline-size
   * @last_test_date 2022-07-14
   * @support 48.98%
   * @partial 0.00%
   * @not_supported 51.02%
   */
  blockSize?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-inline-size/
   * @slug css-inline-size
   * @last_test_date 2019-02-28
   * @support 41.67%
   * @partial 0.00%
   * @not_supported 58.33%
   */
  inlineSize?: AnyString;
  /**
   * Sets whether cells inside a `<table>` have shared or separate borders.
   * @see https://www.caniemail.com/features/css-border-collapse/
   * @slug css-border-collapse
   * @last_test_date 2023-12-20
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderCollapse?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-border-image/
   * @slug css-border-image
   * @last_test_date 2019-02-28
   * @support 48.00%
   * @partial 0.00%
   * @not_supported 52.00%
   */
  borderImage?: AnyString;
  /**
   * Support for the `border-inline` and `border-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-border-inline-block/
   * @slug css-border-inline-block
   * @last_test_date 2022-07-13
   * @support 36.36%
   * @partial 0.00%
   * @not_supported 63.64%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  borderInline?: AnyString;
  /**
   * Support for the `border-inline` and `border-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-border-inline-block/
   * @slug css-border-inline-block
   * @last_test_date 2022-07-13
   * @support 36.36%
   * @partial 0.00%
   * @not_supported 63.64%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  borderBlock?: AnyString;
  /**
   * The `border-radius` CSS property rounds the corners of an element's outer border edge.
   * @see https://www.caniemail.com/features/css-border-radius/
   * @slug css-border-radius
   * @last_test_date 2021-03-09
   * @support 64.15%
   * @partial 11.32%
   * @not_supported 24.53%
   */
  borderRadius?: PropertyValue<T, "radii">;
  /**
   * Sets the distance between the borders of adjacent cells in a `<table>`.
   * @see https://www.caniemail.com/features/css-border-spacing/
   * @slug css-border-spacing
   * @last_test_date 2023-12-20
   * @support 81.25%
   * @partial 0.00%
   * @not_supported 18.75%
   */
  borderSpacing?: AnyString;
  /**
   * The `border` properties set an element's border. This page accounts for all `border` longhands and shorthands.
   * @see https://www.caniemail.com/features/css-border/
   * @slug css-border
   * @last_test_date 2021-07-22
   * @support 87.23%
   * @partial 12.77%
   * @not_supported 0.00%
   * @notes This pages reports support for all CSS properties related to `border`: `border`, `border-width`, `border-style`, `border-color`, `border-top`, `border-bottom`, `border-left`, `border-right`, `border-top-width`, `border-top-style`, `border-top-color`, `border-bottom-width`, `border-bottom-style`, `border-bottom-color`, `border-left-width`, `border-left-style`, `border-left-color`, `border-right-width`, `border-right-style`, `border-right-color`.
   */
  border?: PropertyValue<T, "borders">;
  /**
   * Adds shadow effects around an element's frame.
   * @see https://www.caniemail.com/features/css-box-shadow/
   * @slug css-box-shadow
   * @last_test_date 2023-12-20
   * @support 45.45%
   * @partial 6.06%
   * @not_supported 48.48%
   */
  boxShadow?: PropertyValue<T, "shadows">;
  /**
   * @see https://www.caniemail.com/features/css-box-sizing/
   * @slug css-box-sizing
   * @last_test_date 2019-02-28
   * @support 68.00%
   * @partial 0.00%
   * @not_supported 32.00%
   */
  boxSizing?: AnyString;
  /**
   * The `caption-side` CSS property puts the content of a table's `<caption>` on the specified side.
   * @see https://www.caniemail.com/features/css-caption-side/
   * @slug css-caption-side
   * @last_test_date 2021-05-13
   * @support 88.24%
   * @partial 0.00%
   * @not_supported 11.76%
   */
  captionSide?: AnyString;
  /**
   * Sets whether an element must be moved below (cleared) floating elements that precede it.
   * @see https://www.caniemail.com/features/css-clear/
   * @slug css-clear
   * @last_test_date 2024-09-06
   * @support 32.14%
   * @partial 46.43%
   * @not_supported 21.43%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  clear?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-clip-path/
   * @slug css-clip-path
   * @last_test_date 2021-03-09
   * @support 40.35%
   * @partial 1.75%
   * @not_supported 57.89%
   */
  clipPath?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-column-count/
   * @slug css-column-count
   * @last_test_date 2019-02-28
   * @support 68.09%
   * @partial 0.00%
   * @not_supported 31.91%
   */
  columnCount?: AnyString;
  /**
   * The cursor CSS property sets the mouse cursor, if any, to show when the mouse pointer is over an element.
   * @see https://www.caniemail.com/features/css-cursor/
   * @slug css-cursor
   * @last_test_date 2025-07-02
   * @support 11.11%
   * @partial 27.78%
   * @not_supported 61.11%
   * @notes Cursor appearance on Android mobile devices depends on external pointer device/mouse. Cursor on iOS mobile devices also requires assistive touch to be enabled, and does not appear to respond to content.
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  cursor?: PropertyValue<T, "cursor">;
  /**
   * Sets the direction of text or table columns.
   * @see https://www.caniemail.com/features/css-direction/
   * @slug css-direction
   * @last_test_date 2021-10-05
   * @support 97.83%
   * @partial 2.17%
   * @not_supported 0.00%
   */
  direction?: AnyString;
  /**
   * Sets whether an element is treated as a block or inline element and the layout used for its children.
   * @see https://www.caniemail.com/features/css-display/
   * @slug css-display
   * @last_test_date 2021-12-01
   * @support 56.52%
   * @partial 43.48%
   * @not_supported 0.00%
   */
  display?: AnyString;
  /**
   * Sets whether borders and backgrounds appear around `<table>` cells that have no visible content.
   * @see https://www.caniemail.com/features/css-empty-cells/
   * @slug css-empty-cells
   * @last_test_date 2024-08-23
   * @support 60.00%
   * @partial 0.00%
   * @not_supported 40.00%
   */
  emptyCells?: AnyString;
  /**
   * Tests with values `blur`, `brightness`, `grayscale`, `hue-rotate`, `invert`, `opacity`, `saturate`, `sepia` and `shadow`.
   * @see https://www.caniemail.com/features/css-filter/
   * @slug css-filter
   * @last_test_date 2024-01-03
   * @support 44.00%
   * @partial 2.00%
   * @not_supported 54.00%
   */
  filter?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-float/
   * @slug css-float
   * @last_test_date 2024-05-08
   * @support 68.33%
   * @partial 20.00%
   * @not_supported 11.67%
   */
  float?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-font-kerning/
   * @slug css-font-kerning
   * @last_test_date 2022-08-01
   * @support 66.67%
   * @partial 0.00%
   * @not_supported 33.33%
   */
  fontKerning?: AnyString;
  /**
   * Sets the size of the font.
   * @see https://www.caniemail.com/features/css-font-size/
   * @slug css-font-size
   * @last_test_date 2024-02-28
   * @support 58.82%
   * @partial 41.18%
   * @not_supported 0.00%
   */
  fontSize?: PropertyValue<T, "fontSizes">;
  /**
   * Selecting different font widths (e.g. condensed, expanded)
   * @see https://www.caniemail.com/features/css-font-stretch/
   * @slug css-font-stretch
   * @last_test_date 2023-09-23
   * @support 51.72%
   * @partial 0.00%
   * @not_supported 48.28%
   */
  fontStretch?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-font-weight/
   * @slug css-font-weight
   * @last_test_date 2022-06-23
   * @support 76.56%
   * @partial 23.44%
   * @not_supported 0.00%
   */
  fontWeight?: PropertyValue<T, "fontWeights">;
  /**
   * Sets the character (or string) used at the end of a line before a hyphenation break.
   * @see https://www.caniemail.com/features/css-hyphenate-character/
   * @slug css-hyphenate-character
   * @last_test_date 2024-06-19
   * @support 17.14%
   * @partial 2.86%
   * @not_supported 80.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  hyphenateCharacter?: AnyString;
  /**
   * Specifies the minimum word length to allow hyphenation of words as well as the minimum number of characters before and after the hyphen.
   * @see https://www.caniemail.com/features/css-hyphenate-limit-chars/
   * @slug css-hyphenate-limit-chars
   * @last_test_date 2024-08-08
   * @support 3.85%
   * @partial 0.00%
   * @not_supported 96.15%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  hyphenateLimitChars?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-hyphens/
   * @slug css-hyphens
   * @last_test_date 2022-08-03
   * @support 47.22%
   * @partial 0.00%
   * @not_supported 52.78%
   */
  hyphens?: AnyString;
  /**
   * Shorthand that corresponds to the `top`, `right`, `bottom`, and/or `left` properties
   * @see https://www.caniemail.com/features/css-inset/
   * @slug css-inset
   * @last_test_date 2024-05-29
   * @support 12.00%
   * @partial 0.00%
   * @not_supported 88.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  inset?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-justify-content/
   * @slug css-justify-content
   * @last_test_date 2021-03-09
   * @support 57.63%
   * @partial 0.00%
   * @not_supported 42.37%
   */
  justifyContent?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-letter-spacing/
   * @slug css-letter-spacing
   * @last_test_date 2020-01-19
   * @support 87.76%
   * @partial 12.24%
   * @not_supported 0.00%
   */
  letterSpacing?: PropertyValue<T, "letterSpacings">;
  /**
   * Sets the height of a line box. Or, basically, the height of a line of text.
   * @see https://www.caniemail.com/features/css-line-height/
   * @slug css-line-height
   * @last_test_date 2021-10-02
   * @support 82.98%
   * @partial 17.02%
   * @not_supported 0.00%
   */
  lineHeight?: PropertyValue<T, "lineHeights">;
  /**
   * @see https://www.caniemail.com/features/css-list-style-image/
   * @slug css-list-style-image
   * @last_test_date 2020-04-20
   * @support 52.00%
   * @partial 0.00%
   * @not_supported 48.00%
   */
  listStyleImage?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-list-style-position/
   * @slug css-list-style-position
   * @last_test_date 2020-04-20
   * @support 88.00%
   * @partial 0.00%
   * @not_supported 12.00%
   */
  listStylePosition?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-list-style-type/
   * @slug css-list-style-type
   * @last_test_date 2020-04-20
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   * @notes Tests and support are based on the CSS Level 2 specification. `<custom-ident>`, `symbols()` and `<string>` values are not tested here.
   */
  listStyleType?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-list-style/
   * @slug css-list-style
   * @last_test_date 2020-04-20
   * @support 62.00%
   * @partial 36.00%
   * @not_supported 2.00%
   * @notes Tests and support are based on the CSS Level 2 specification. `<custom-ident>`, `symbols()` and `<string>` values are not tested here.
   */
  listStyle?: AnyString;
  /**
   * Support for the `margin-block-start` and `margin-block-end` css properties.
   * @see https://www.caniemail.com/features/css-margin-block-start-end/
   * @slug css-margin-block-start-end
   * @last_test_date 2022-07-13
   * @support 45.45%
   * @partial 0.00%
   * @not_supported 54.55%
   */
  marginBlockStart?: AnyString;
  /**
   * Support for the `margin-block-start` and `margin-block-end` css properties.
   * @see https://www.caniemail.com/features/css-margin-block-start-end/
   * @slug css-margin-block-start-end
   * @last_test_date 2022-07-13
   * @support 45.45%
   * @partial 0.00%
   * @not_supported 54.55%
   */
  marginBlockEnd?: AnyString;
  /**
   * Support for the `margin-inline` and `margin-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-margin-inline-block/
   * @slug css-margin-inline-block
   * @last_test_date 2022-07-12
   * @support 41.82%
   * @partial 0.00%
   * @not_supported 58.18%
   */
  marginInline?: AnyString;
  /**
   * Support for the `margin-inline` and `margin-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-margin-inline-block/
   * @slug css-margin-inline-block
   * @last_test_date 2022-07-12
   * @support 41.82%
   * @partial 0.00%
   * @not_supported 58.18%
   */
  marginBlock?: AnyString;
  /**
   * Support for the `margin-inline-start` and `margin-inline-end` css properties.
   * @see https://www.caniemail.com/features/css-margin-inline-start-end/
   * @slug css-margin-inline-start-end
   * @last_test_date 2022-07-13
   * @support 45.45%
   * @partial 0.00%
   * @not_supported 54.55%
   */
  marginInlineStart?: AnyString;
  /**
   * Support for the `margin-inline-start` and `margin-inline-end` css properties.
   * @see https://www.caniemail.com/features/css-margin-inline-start-end/
   * @slug css-margin-inline-start-end
   * @last_test_date 2022-07-13
   * @support 45.45%
   * @partial 0.00%
   * @not_supported 54.55%
   */
  marginInlineEnd?: AnyString;
  /**
   * Support for the `margin` shorthand property and the `margin-left`, `margin-right`, `margin-top`, `margin-bottom` properties.
   * @see https://www.caniemail.com/features/css-margin/
   * @slug css-margin
   * @last_test_date 2019-10-01
   * @support 61.40%
   * @partial 38.60%
   * @not_supported 0.00%
   */
  margin?: PropertyValue<T, "spacing">;
  /**
   * Sets the image that is used as mask layer for an element
   * @see https://www.caniemail.com/features/css-mask-image/
   * @slug css-mask-image
   * @last_test_date 2024-11-27
   * @support 27.03%
   * @partial 0.00%
   * @not_supported 72.97%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  maskImage?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-max-block-size/
   * @slug css-max-block-size
   * @last_test_date 2022-09-01
   * @support 50.00%
   * @partial 0.00%
   * @not_supported 50.00%
   */
  maxBlockSize?: AnyString;
  /**
   * Defines the horizontal or vertical maximum size of an element's block, depending on its writing mode
   * @see https://www.caniemail.com/features/css-max-inline-size/
   * @slug css-max-inline-size
   * @last_test_date 2024-05-31
   * @support 25.00%
   * @partial 0.00%
   * @not_supported 75.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  maxInlineSize?: AnyString;
  /**
   * This is the description of the `max-width` property.
   * @see https://www.caniemail.com/features/css-max-width/
   * @slug css-max-width
   * @last_test_date 2019-08-02
   * @support 78.57%
   * @partial 14.29%
   * @not_supported 7.14%
   */
  maxWidth?: PropertyValue<T, "sizes">;
  /**
   * Defines the minimum horizontal or vertical size of an element's block, depending on its writing mode
   * @see https://www.caniemail.com/features/css-min-block-size/
   * @slug css-min-block-size
   * @last_test_date 2024-05-31
   * @support 25.00%
   * @partial 0.00%
   * @not_supported 75.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  minBlockSize?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-min-inline-size/
   * @slug css-min-inline-size
   * @last_test_date 2022-08-30
   * @support 48.65%
   * @partial 0.00%
   * @not_supported 51.35%
   */
  minInlineSize?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-mix-blend-mode/
   * @slug css-mix-blend-mode
   * @last_test_date 2020-12-12
   * @support 60.71%
   * @partial 3.57%
   * @not_supported 35.71%
   */
  mixBlendMode?: AnyString;
  /**
   * The `object-fit` CSS property sets how the content of a replaced element, such as an `<img>` or `<video>`, should be resized to fit its container.
   * @see https://www.caniemail.com/features/css-object-fit/
   * @slug css-object-fit
   * @last_test_date 2021-07-15
   * @support 58.82%
   * @partial 3.92%
   * @not_supported 37.25%
   */
  objectFit?: AnyString;
  /**
   * The `object-position` CSS property specifies the alignment of the selected replaced element's contents within the element's box. Areas of the box which aren't covered by the replaced element's object will show the element's background.
   * @see https://www.caniemail.com/features/css-object-position/
   * @slug css-object-position
   * @last_test_date 2021-07-15
   * @support 56.86%
   * @partial 3.92%
   * @not_supported 39.22%
   */
  objectPosition?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-opacity/
   * @slug css-opacity
   * @last_test_date 2019-02-28
   * @support 62.96%
   * @partial 0.00%
   * @not_supported 37.04%
   */
  opacity?: PropertyValue<T, "opacity">;
  /**
   * Sets the minimum number of lines in a block container split on an old page, region or column.
   * @see https://www.caniemail.com/features/css-orphans/
   * @slug css-orphans
   * @last_test_date 2024-06-13
   * @support 39.29%
   * @partial 0.00%
   * @not_supported 60.71%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  orphans?: AnyString;
  /**
   * Controls the position of an outline.
   * @see https://www.caniemail.com/features/css-outline-offset/
   * @slug css-outline-offset
   * @last_test_date 2022-12-26
   * @support 40.48%
   * @partial 0.00%
   * @not_supported 59.52%
   */
  outlineOffset?: AnyString;
  /**
   * Sets a line outside of the element's border.
   * @see https://www.caniemail.com/features/css-outline/
   * @slug css-outline
   * @last_test_date 2022-03-17
   * @support 81.63%
   * @partial 0.00%
   * @not_supported 18.37%
   * @notes WebKit renders square outline even when using `border-radius`.
   */
  outline?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-overflow-wrap/
   * @slug css-overflow-wrap
   * @last_test_date 2022-08-03
   * @support 12.50%
   * @partial 8.33%
   * @not_supported 79.17%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  overflowWrap?: AnyString;
  /**
   * Sets the desired behavior when content does not fit in the element's padding box
   * @see https://www.caniemail.com/features/css-overflow/
   * @slug css-overflow
   * @last_test_date 2025-05-27
   * @support 47.50%
   * @partial 40.00%
   * @not_supported 12.50%
   */
  overflow?: AnyString;
  /**
   * Support for the `padding-block-start` and `padding-block-end` css properties.
   * @see https://www.caniemail.com/features/css-padding-block-start-end/
   * @slug css-padding-block-start-end
   * @last_test_date 2022-07-13
   * @support 44.44%
   * @partial 0.00%
   * @not_supported 55.56%
   */
  paddingBlockStart?: AnyString;
  /**
   * Support for the `padding-block-start` and `padding-block-end` css properties.
   * @see https://www.caniemail.com/features/css-padding-block-start-end/
   * @slug css-padding-block-start-end
   * @last_test_date 2022-07-13
   * @support 44.44%
   * @partial 0.00%
   * @not_supported 55.56%
   */
  paddingBlockEnd?: AnyString;
  /**
   * Support for the `padding-inline` and `padding-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-padding-inline-block/
   * @slug css-padding-inline-block
   * @last_test_date 2022-07-13
   * @support 26.67%
   * @partial 0.00%
   * @not_supported 73.33%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  paddingInline?: AnyString;
  /**
   * Support for the `padding-inline` and `padding-block` shorthand properties.
   * @see https://www.caniemail.com/features/css-padding-inline-block/
   * @slug css-padding-inline-block
   * @last_test_date 2022-07-13
   * @support 26.67%
   * @partial 0.00%
   * @not_supported 73.33%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  paddingBlock?: AnyString;
  /**
   * Support for the `padding-inline-start` and `padding-inline-end` css properties.
   * @see https://www.caniemail.com/features/css-padding-inline-start-end/
   * @slug css-padding-inline-start-end
   * @last_test_date 2022-07-13
   * @support 44.44%
   * @partial 0.00%
   * @not_supported 55.56%
   */
  paddingInlineStart?: AnyString;
  /**
   * Support for the `padding-inline-start` and `padding-inline-end` css properties.
   * @see https://www.caniemail.com/features/css-padding-inline-start-end/
   * @slug css-padding-inline-start-end
   * @last_test_date 2022-07-13
   * @support 44.44%
   * @partial 0.00%
   * @not_supported 55.56%
   */
  paddingInlineEnd?: AnyString;
  /**
   * This test includes support for the `padding` shorthand property as well as for `padding-left`, `padding-right`, `padding-top` and `padding-bottom`.
   * @see https://www.caniemail.com/features/css-padding/
   * @slug css-padding
   * @last_test_date 2019-07-25
   * @support 88.24%
   * @partial 11.76%
   * @not_supported 0.00%
   */
  padding?: PropertyValue<T, "spacing">;
  /**
   * Tests for CSS positioning include `relative`, `absolute`, `fixed` and `sticky`.
   * @see https://www.caniemail.com/features/css-position/
   * @slug css-position
   * @last_test_date 2021-05-16
   * @support 29.17%
   * @partial 45.83%
   * @not_supported 25.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  position?: AnyString;
  /**
   * Sets whether an element is resizable, and in which directions.
   * @see https://www.caniemail.com/features/css-resize/
   * @slug css-resize
   * @last_test_date 2024-01-17
   * @support 6.90%
   * @partial 3.45%
   * @not_supported 89.66%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  resize?: AnyString;
  /**
   * Controls panning and scrolling behaviour with snap positions.
   * @see https://www.caniemail.com/features/css-scroll-snap/
   * @slug css-scroll-snap
   * @last_test_date 2023-02-27
   * @support 36.84%
   * @partial 0.00%
   * @not_supported 63.16%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  scrollSnap?: AnyString;
  /**
   * Sets a margin for a CSS shape created using `shape-outside`
   * @see https://www.caniemail.com/features/css-shape-margin/
   * @slug css-shape-margin
   * @last_test_date 2024-03-13
   * @support 25.00%
   * @partial 0.00%
   * @not_supported 75.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  shapeMargin?: AnyString;
  /**
   * Defines a shape, which may be non-rectangular, around which adjacent inline content should wrap.
   * @see https://www.caniemail.com/features/css-shape-outside/
   * @slug css-shape-outside
   * @last_test_date 2024-02-28
   * @support 25.00%
   * @partial 0.00%
   * @not_supported 75.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  shapeOutside?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-tab-size/
   * @slug css-tab-size
   * @last_test_date 2022-07-21
   * @support 52.27%
   * @partial 0.00%
   * @not_supported 47.73%
   */
  tabSize?: AnyString;
  /**
   * The table-layout property defines the algorithm used to lay out table cells, rows, and columns.
   * @see https://www.caniemail.com/features/css-table-layout/
   * @slug css-table-layout
   * @last_test_date 2022-07-20
   * @support 77.78%
   * @partial 0.00%
   * @not_supported 22.22%
   */
  tableLayout?: AnyString;
  /**
   * The `text-align-last` CSS property sets how the last line of a block or a line right before a forced line break is aligned.
   * @see https://www.caniemail.com/features/css-text-align-last/
   * @slug css-text-align-last
   * @last_test_date 2022-08-31
   * @support 41.18%
   * @partial 0.00%
   * @not_supported 58.82%
   */
  textAlignLast?: AnyString;
  /**
   * Sets the horizontal alignment of the content.
   * @see https://www.caniemail.com/features/css-text-align/
   * @slug css-text-align
   * @last_test_date 2021-09-24
   * @support 66.00%
   * @partial 34.00%
   * @not_supported 0.00%
   */
  textAlign?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-text-decoration-color/
   * @slug css-text-decoration-color
   * @last_test_date 2020-04-30
   * @support 68.63%
   * @partial 9.80%
   * @not_supported 21.57%
   * @notes `text-decoration-color` is not supported in Internet Explorer.
   */
  textDecorationColor?: AnyString;
  /**
   * Sets the kind of decoration that is used on text in an element, such as an underline or overline.
   * @see https://www.caniemail.com/features/css-text-decoration-line/
   * @slug css-text-decoration-line
   * @last_test_date 2023-12-06
   * @support 71.43%
   * @partial 0.00%
   * @not_supported 28.57%
   */
  textDecorationLine?: AnyString;
  /**
   * Specifies how overlines and underlines are drawn when they pass over glyph ascenders and descenders.
   * @see https://www.caniemail.com/features/css-text-decoration-skip-ink/
   * @slug css-text-decoration-skip-ink
   * @last_test_date 2023-12-08
   * @support 33.33%
   * @partial 0.00%
   * @not_supported 66.67%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textDecorationSkipInk?: AnyString;
  /**
   * Sets the style of the lines specified by text-decoration-line.
   * @see https://www.caniemail.com/features/css-text-decoration-style/
   * @slug css-text-decoration-style
   * @last_test_date 2023-12-06
   * @support 71.43%
   * @partial 0.00%
   * @not_supported 28.57%
   */
  textDecorationStyle?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-text-decoration-thickness/
   * @slug css-text-decoration-thickness
   * @last_test_date 2023-01-16
   * @support 37.10%
   * @partial 1.61%
   * @not_supported 61.29%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textDecorationThickness?: AnyString;
  /**
   * Tested with the values `overline`, `underline` and `line-through`.
   * @see https://www.caniemail.com/features/css-text-decoration/
   * @slug css-text-decoration
   * @last_test_date 2019-02-28
   * @support 68.75%
   * @partial 25.00%
   * @not_supported 6.25%
   */
  textDecoration?: AnyString;
  /**
   * Determines the position of the emphasis mark.
   * @see https://www.caniemail.com/features/css-text-emphasis-position/
   * @slug css-text-emphasis-position
   * @last_test_date 2022-07-07
   * @support 43.90%
   * @partial 0.00%
   * @not_supported 56.10%
   */
  textEmphasisPosition?: AnyString;
  /**
   * Applies emphasis marks to text commonly used in East Asian languages. Tests with text-emphasis, text-emphasis-color & text-emphasis-style properties.
   * @see https://www.caniemail.com/features/css-text-emphasis/
   * @slug css-text-emphasis
   * @last_test_date 2022-07-07
   * @support 56.10%
   * @partial 0.00%
   * @not_supported 43.90%
   */
  textEmphasis?: AnyString;
  /**
   * Support below refers to supporting a `<length>` value only. This does not include the new `each-line` or `hanging` keywords.
   * @see https://www.caniemail.com/features/css-text-indent/
   * @slug css-text-indent
   * @last_test_date 2021-01-31
   * @support 79.25%
   * @partial 20.75%
   * @not_supported 0.00%
   */
  textIndent?: AnyString;
  /**
   * Sets what type of justification should be applied to text when `text-align: justify;` is set on an element.
   * @see https://www.caniemail.com/features/css-text-justify/
   * @slug css-text-justify
   * @last_test_date 2024-04-17
   * @support 0.00%
   * @partial 40.00%
   * @not_supported 60.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textJustify?: AnyString;
  /**
   * Sets the orientation of the text characters in vertical mode.
   * @see https://www.caniemail.com/features/css-text-orientation/
   * @slug css-text-orientation
   * @last_test_date 2023-12-08
   * @support 58.00%
   * @partial 2.00%
   * @not_supported 40.00%
   */
  textOrientation?: AnyString;
  /**
   * Tested with the value `ellipsis`.
   * @see https://www.caniemail.com/features/css-text-overflow/
   * @slug css-text-overflow
   * @last_test_date 2019-02-28
   * @support 60.42%
   * @partial 4.17%
   * @not_supported 35.42%
   */
  textOverflow?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-text-shadow/
   * @slug css-text-shadow
   * @last_test_date 2019-02-28
   * @support 67.35%
   * @partial 0.00%
   * @not_supported 32.65%
   */
  textShadow?: AnyString;
  /**
   * Each of the six `text-transform` values defined by MDN (`capitalize`, `uppercase`, `lowercase`, `none`, `full-width`, `full-size-kana`).
   * @see https://www.caniemail.com/features/css-text-transform/
   * @slug css-text-transform
   * @last_test_date 2021-09-19
   * @support 87.23%
   * @partial 12.77%
   * @not_supported 0.00%
   * @notes Currently, only Firefox supports the `full-width` and `full-size-kana` property values. Web clients on Firefox will support these properties.
   */
  textTransform?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-text-underline-offset/
   * @slug css-text-underline-offset
   * @last_test_date 2023-01-16
   * @support 37.93%
   * @partial 0.00%
   * @not_supported 62.07%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textUnderlineOffset?: AnyString;
  /**
   * Specifies the position of the underline which is set using the `text-decoration property`'s underline value.
   * @see https://www.caniemail.com/features/css-text-underline-position/
   * @slug css-text-underline-position
   * @last_test_date 2023-12-08
   * @support 38.71%
   * @partial 12.90%
   * @not_supported 48.39%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textUnderlinePosition?: AnyString;
  /**
   * Controls how text inside an element is wrapped
   * @see https://www.caniemail.com/features/css-text-wrap/
   * @slug css-text-wrap
   * @last_test_date 2024-04-03
   * @support 18.52%
   * @partial 0.00%
   * @not_supported 81.48%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  textWrap?: AnyString;
  /**
   * Tested with values `matrix`, `translate`, `scale`, `rotate`, `skew`, `scale translate`.
   * @see https://www.caniemail.com/features/css-transform/
   * @slug css-transform
   * @last_test_date 2019-02-28
   * @support 45.10%
   * @partial 0.00%
   * @not_supported 54.90%
   */
  transform?: AnyString;
  /**
   * Creates a visual transition when changing CSS properties.
   * @see https://www.caniemail.com/features/css-transition/
   * @slug css-transition
   * @last_test_date 2024-03-29
   * @support 24.32%
   * @partial 21.62%
   * @not_supported 54.05%
   * @notes This page accounts for the shorthand `transition` property and the longhand properties `transition-delay`, `transition-duration`, `transition-property` and `transition-timing-function`.
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  transition?: AnyString;
  /**
   * Controls whether the user can select text.
   * @see https://www.caniemail.com/features/css-user-select/
   * @slug css-user-select
   * @last_test_date 2024-02-14
   * @support 10.71%
   * @partial 14.29%
   * @not_supported 75.00%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  userSelect?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-vertical-align/
   * @slug css-vertical-align
   * @last_test_date 2020-12-21
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  verticalAlign?: AnyString;
  /**
   * Tested for values `hidden` and `collapse`.
   * @see https://www.caniemail.com/features/css-visibility/
   * @slug css-visibility
   * @last_test_date 2019-02-28
   * @support 67.31%
   * @partial 3.85%
   * @not_supported 28.85%
   */
  visibility?: AnyString;
  /**
   * Controls how white space inside an element is collapsed.
   * @see https://www.caniemail.com/features/css-white-space-collapse/
   * @slug css-white-space-collapse
   * @last_test_date 2024-09-04
   * @support 23.33%
   * @partial 0.00%
   * @not_supported 76.67%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  whiteSpaceCollapse?: AnyString;
  /**
   * Tested with the values `nowrap` and `pre`.
   * @see https://www.caniemail.com/features/css-white-space/
   * @slug css-white-space
   * @last_test_date 2019-02-28
   * @support 68.75%
   * @partial 16.67%
   * @not_supported 14.58%
   */
  whiteSpace?: AnyString;
  /**
   * Sets the minimum number of lines in a block container split on a new page, region or column.
   * @see https://www.caniemail.com/features/css-widows/
   * @slug css-widows
   * @last_test_date 2024-05-03
   * @support 39.29%
   * @partial 0.00%
   * @not_supported 60.71%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  widows?: AnyString;
  /**
   * Prevents or allows words to be broken over multiple lines.
   * @see https://www.caniemail.com/features/css-word-break/
   * @slug css-word-break
   * @last_test_date 2022-02-15
   * @support 32.56%
   * @partial 34.88%
   * @not_supported 32.56%
   * @deprecated poor support coverage. This property might not work as expected in many email clients.
   */
  wordBreak?: AnyString;
  /**
   * Sets the length of space between words and between tags.
   * @see https://www.caniemail.com/features/css-word-spacing/
   * @slug css-word-spacing
   * @last_test_date 2024-03-13
   * @support 53.33%
   * @partial 23.33%
   * @not_supported 23.33%
   */
  wordSpacing?: AnyString;
  /**
   * The word-wrap CSS property (now standardized as overflow-wrap) controls whether the browser should break words to prevent them from overflowing their container. When set to break-word, it forces otherwise unbreakable strings to wrap onto the next line to avoid layout issues.
   * @see https://www.caniemail.com/features/css-word-wrap/
   * @slug css-word-wrap
   * @last_test_date 2025-05-08
   * @support 41.67%
   * @partial 16.67%
   * @not_supported 41.67%
   */
  wordWrap?: AnyString;
  /**
   * Sets whether lines of text are laid out horizontally or vertically.
   * @see https://www.caniemail.com/features/css-writing-mode/
   * @slug css-writing-mode
   * @last_test_date 2022-05-04
   * @support 58.00%
   * @partial 4.00%
   * @not_supported 38.00%
   */
  writingMode?: AnyString;
  /**
   * @see https://www.caniemail.com/features/css-z-index/
   * @slug css-z-index
   * @last_test_date 2021-05-16
   * @support 77.08%
   * @partial 0.00%
   * @not_supported 22.92%
   */
  zIndex?: PropertyValue<T, "zIndex">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundPositionX?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundPositionY?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundRepeatX?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundRepeatY?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundAttachment?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  backgroundComposite?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderWidth?: PropertyValue<T, "borderWidths">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderStyle?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderColor?: PropertyValue<T, "colors">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderTopRadius?: PropertyValue<T, "radii">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderRightRadius?: PropertyValue<T, "radii">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderBottomRadius?: PropertyValue<T, "radii">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  borderLeftRadius?: PropertyValue<T, "radii">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  top?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  bottom?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  left?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  right?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  flex?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  flexDirection?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  gap?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  columnGap?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  rowGap?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  pointerEvents?: AnyString;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  width?: PropertyValue<T, "sizes">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  height?: PropertyValue<T, "sizes">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  minWidth?: PropertyValue<T, "sizes">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  minHeight?: PropertyValue<T, "sizes">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  maxHeight?: PropertyValue<T, "sizes">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginTop?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginRight?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginBottom?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginLeft?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginX?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  marginY?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingTop?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingRight?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingBottom?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingLeft?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingX?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  paddingY?: PropertyValue<T, "spacing">;
  /**
   * @support 100.00%
   * @partial 0.00%
   * @not_supported 0.00%
   */
  color?: PropertyValue<T, "colors">;
}
