// This file is auto-generated by src/scripts/can-i-email.ts
// Do not edit this file manually.

export const canIEmailCSSAtRules = {
  "@font-face": {
    "slug": "css-at-font-face",
    "description": "`@font-face` in CSS allows to include your own fonts inside an email.",
    "url": "https://www.caniemail.com/features/css-at-font-face/",
    "last_test_date": "2023-12-19",
    "coverage": {
      "support": 27.11864406779661,
      "partial": 16.94915254237288,
      "notSupported": 55.932203389830505
    },
    "notes": null,
    "type": "string"
  },
  "@import": {
    "slug": "css-at-import",
    "description": "This is the description of the `@import` property.",
    "url": "https://www.caniemail.com/features/css-at-import/",
    "last_test_date": "2019-02-28",
    "coverage": {
      "support": 31.48148148148148,
      "partial": 0,
      "notSupported": 68.51851851851852
    },
    "notes": null,
    "type": "string"
  },
  "@keyframes": {
    "slug": "css-at-keyframes",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-keyframes/",
    "last_test_date": "2021-05-25",
    "coverage": {
      "support": 30,
      "partial": 6,
      "notSupported": 64
    },
    "notes": null,
    "type": "string"
  },
  "@media": {
    "slug": "css-at-media",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-media/",
    "last_test_date": "2023-12-13",
    "coverage": {
      "support": 36.231884057971016,
      "partial": 42.028985507246375,
      "notSupported": 21.73913043478261
    },
    "notes": null,
    "type": "string"
  },
  "@supports": {
    "slug": "css-at-supports",
    "description": null,
    "url": "https://www.caniemail.com/features/css-at-supports/",
    "last_test_date": "2020-05-25",
    "coverage": {
      "support": 50,
      "partial": 0,
      "notSupported": 50
    },
    "notes": null,
    "type": "string"
  }
} as const;
