// This file is auto-generated by src/scripts/can-i-email.ts
// Do not edit this file manually.

export const canIEmailCSSValues = {
  "display:flex": {
    "slug": "css-display-flex",
    "description": "",
    "url": "https://www.caniemail.com/features/css-display-flex/",
    "last_test_date": "2021-11-02",
    "coverage": {
      "support": 61.29032258064516,
      "partial": 6.451612903225806,
      "notSupported": 32.25806451612903
    },
    "notes": null,
    "type": "string"
  },
  "display:grid": {
    "slug": "css-display-grid",
    "description": "",
    "url": "https://www.caniemail.com/features/css-display-grid/",
    "last_test_date": "2019-02-28",
    "coverage": {
      "support": 52.94117647058824,
      "partial": 0,
      "notSupported": 47.05882352941176
    },
    "notes": null,
    "type": "string"
  },
  "display:none": {
    "slug": "css-display-none",
    "description": "",
    "url": "https://www.caniemail.com/features/css-display-none/",
    "last_test_date": "2019-02-28",
    "coverage": {
      "support": 85.1063829787234,
      "partial": 12.76595744680851,
      "notSupported": 2.127659574468085
    },
    "notes": null,
    "type": "string"
  },
  "flex-direction:column": {
    "slug": "css-flex-direction",
    "description": "",
    "url": "https://www.caniemail.com/features/css-flex-direction/",
    "last_test_date": "2023-01-17",
    "coverage": {
      "support": 48.214285714285715,
      "partial": 0,
      "notSupported": 51.78571428571429
    },
    "notes": null,
    "type": "string"
  },
  ":active": {
    "slug": "css-pseudo-class-active",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-active/",
    "last_test_date": "2019-10-28",
    "coverage": {
      "support": 50.98039215686274,
      "partial": 7.8431372549019605,
      "notSupported": 41.17647058823529
    },
    "notes": null,
    "type": "string"
  },
  ":checked": {
    "slug": "css-pseudo-class-checked",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-checked/",
    "last_test_date": "2020-03-10",
    "coverage": {
      "support": 29.411764705882355,
      "partial": 9.803921568627452,
      "notSupported": 60.78431372549019
    },
    "notes": null,
    "type": "string"
  },
  ":default": {
    "slug": "css-pseudo-class-default",
    "description": "Selects form elements that are the default in a group of related elements.",
    "url": "https://www.caniemail.com/features/css-pseudo-class-default/",
    "last_test_date": "2026-02-05",
    "coverage": {
      "support": 45.714285714285715,
      "partial": 2.857142857142857,
      "notSupported": 51.42857142857142
    },
    "notes": "Depends on device/browser support. Some devices/browsers do not support styling on &lt;option&gt;.",
    "type": "string"
  },
  ":first-child": {
    "slug": "css-pseudo-class-first-child",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-first-child/",
    "last_test_date": "2019-10-16",
    "coverage": {
      "support": 61.53846153846154,
      "partial": 5.769230769230769,
      "notSupported": 32.69230769230769
    },
    "notes": null,
    "type": "string"
  },
  ":first-of-type": {
    "slug": "css-pseudo-class-first-of-type",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-first-of-type/",
    "last_test_date": "2019-10-16",
    "coverage": {
      "support": 57.692307692307686,
      "partial": 5.769230769230769,
      "notSupported": 36.53846153846153
    },
    "notes": null,
    "type": "string"
  },
  ":focus": {
    "slug": "css-pseudo-class-focus",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-focus/",
    "last_test_date": "2019-10-28",
    "coverage": {
      "support": 49.01960784313725,
      "partial": 5.88235294117647,
      "notSupported": 45.09803921568628
    },
    "notes": null,
    "type": "string"
  },
  ":hover": {
    "slug": "css-pseudo-class-hover",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-hover/",
    "last_test_date": "2019-10-23",
    "coverage": {
      "support": 59.61538461538461,
      "partial": 7.6923076923076925,
      "notSupported": 32.69230769230769
    },
    "notes": null,
    "type": "string"
  },
  ":last-child": {
    "slug": "css-pseudo-class-last-child",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-last-child/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 59.61538461538461,
      "partial": 5.769230769230769,
      "notSupported": 34.61538461538461
    },
    "notes": null,
    "type": "string"
  },
  ":last-of-type": {
    "slug": "css-pseudo-class-last-of-type",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-last-of-type/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 55.769230769230774,
      "partial": 5.769230769230769,
      "notSupported": 38.46153846153847
    },
    "notes": null,
    "type": "string"
  },
  ":link": {
    "slug": "css-pseudo-class-link",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-link/",
    "last_test_date": "2019-10-23",
    "coverage": {
      "support": 75.47169811320755,
      "partial": 3.7735849056603774,
      "notSupported": 20.754716981132077
    },
    "notes": null,
    "type": "string"
  },
  ":not": {
    "slug": "css-pseudo-class-not",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-not/",
    "last_test_date": "2019-10-23",
    "coverage": {
      "support": 41.509433962264154,
      "partial": 0,
      "notSupported": 58.490566037735846
    },
    "notes": null,
    "type": "string"
  },
  ":nth-child": {
    "slug": "css-pseudo-class-nth-child",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-nth-child/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 41.509433962264154,
      "partial": 1.8867924528301887,
      "notSupported": 56.60377358490566
    },
    "notes": null,
    "type": "string"
  },
  ":nth-last-child": {
    "slug": "css-pseudo-class-nth-last-child",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-nth-last-child/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 41.509433962264154,
      "partial": 1.8867924528301887,
      "notSupported": 56.60377358490566
    },
    "notes": null,
    "type": "string"
  },
  ":nth-last-of-type": {
    "slug": "css-pseudo-class-nth-last-of-type",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-nth-last-of-type/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 39.62264150943396,
      "partial": 1.8867924528301887,
      "notSupported": 58.490566037735846
    },
    "notes": null,
    "type": "string"
  },
  ":nth-of-type": {
    "slug": "css-pseudo-class-nth-of-type",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-nth-of-type/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 39.62264150943396,
      "partial": 1.8867924528301887,
      "notSupported": 58.490566037735846
    },
    "notes": null,
    "type": "string"
  },
  ":only-child": {
    "slug": "css-pseudo-class-only-child",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-only-child/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 59.61538461538461,
      "partial": 5.769230769230769,
      "notSupported": 34.61538461538461
    },
    "notes": null,
    "type": "string"
  },
  ":only-of-type": {
    "slug": "css-pseudo-class-only-of-type",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-only-of-type/",
    "last_test_date": "2019-10-19",
    "coverage": {
      "support": 59.61538461538461,
      "partial": 5.769230769230769,
      "notSupported": 34.61538461538461
    },
    "notes": null,
    "type": "string"
  },
  ":target": {
    "slug": "css-pseudo-class-target",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-target/",
    "last_test_date": "2019-10-28",
    "coverage": {
      "support": 36,
      "partial": 6,
      "notSupported": 57.99999999999999
    },
    "notes": null,
    "type": "string"
  },
  ":visited": {
    "slug": "css-pseudo-class-visited",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-class-visited/",
    "last_test_date": "2019-10-28",
    "coverage": {
      "support": 36,
      "partial": 6,
      "notSupported": 57.99999999999999
    },
    "notes": null,
    "type": "string"
  },
  "::after": {
    "slug": "css-pseudo-element-after",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-element-after/",
    "last_test_date": "2020-05-21",
    "coverage": {
      "support": 34.48275862068966,
      "partial": 6.896551724137931,
      "notSupported": 58.620689655172406
    },
    "notes": null,
    "type": "string"
  },
  "::before": {
    "slug": "css-pseudo-element-before",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-element-before/",
    "last_test_date": "2020-05-21",
    "coverage": {
      "support": 34.48275862068966,
      "partial": 6.896551724137931,
      "notSupported": 58.620689655172406
    },
    "notes": null,
    "type": "string"
  },
  "::first-letter": {
    "slug": "css-pseudo-element-first-letter",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-element-first-letter/",
    "last_test_date": "2020-05-21",
    "coverage": {
      "support": 54.54545454545454,
      "partial": 7.2727272727272725,
      "notSupported": 38.18181818181819
    },
    "notes": null,
    "type": "string"
  },
  "::first-line": {
    "slug": "css-pseudo-element-first-line",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-element-first-line/",
    "last_test_date": "2020-05-21",
    "coverage": {
      "support": 54.54545454545454,
      "partial": 7.2727272727272725,
      "notSupported": 38.18181818181819
    },
    "notes": null,
    "type": "string"
  },
  "::marker": {
    "slug": "css-pseudo-element-marker",
    "description": "Selects the marker box of a list item (typically a bullet or number).",
    "url": "https://www.caniemail.com/features/css-pseudo-element-marker/",
    "last_test_date": "2022-12-28",
    "coverage": {
      "support": 44.18604651162791,
      "partial": 0,
      "notSupported": 55.81395348837209
    },
    "notes": null,
    "type": "string"
  },
  "::placeholder": {
    "slug": "css-pseudo-element-placeholder",
    "description": null,
    "url": "https://www.caniemail.com/features/css-pseudo-element-placeholder/",
    "last_test_date": "2020-05-21",
    "coverage": {
      "support": 29.09090909090909,
      "partial": 7.2727272727272725,
      "notSupported": 63.63636363636363
    },
    "notes": null,
    "type": "string"
  }
} as const;
