// This file is auto-generated by src/scripts/can-i-email.js
// Do not edit this file manually.

export const canIEmailCSSAtRules = {
  "@font-face": {
    "slug": "css-at-font-face",
    "description": "`@font-face` in CSS allows to include your own fonts inside an email.",
    "url": "https://www.caniemail.com/features/css-at-font-face/",
    "last_test_date": "2023-12-19",
    "stats": {
      "apple-mail": {
        "macos": {
          "12.2": "y"
        },
        "ios": {
          "10.3": "y",
          "12.3.1": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2019-07": "n #6"
        },
        "ios": {
          "2019-07": "n"
        },
        "android": {
          "2019-07": "n"
        },
        "mobile-webmail": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-05": "a #2",
          "2021-03": "n #7",
          "2024-03": "n"
        },
        "ios": {
          "2019-07": "y",
          "2024-03": "n"
        },
        "android": {
          "2019-07": "a #1",
          "2024-04": "n"
        }
      },
      "outlook": {
        "windows": {
          "2003": "a #3",
          "2007": "a #4 #5",
          "2010": "a #4 #5",
          "2013": "a #4 #5",
          "2016": "a #4 #5",
          "2019": "a #4"
        },
        "windows-mail": {
          "2020-01": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2019-07": "n",
          "2023-12": "n"
        },
        "ios": {
          "2.51.1": "y",
          "3.29.0": "n"
        },
        "android": {
          "2019-07": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "y #8",
          "2021-11": "y #8"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-07": "a #2",
          "2025-07": "n"
        },
        "ios": {
          "2019-07": "n"
        },
        "android": {
          "2019-07": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.7": "y",
          "78.5": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-01": "n"
        },
        "ios": {
          "2020-01": "n"
        },
        "android": {
          "2020-01": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2019-07": "n"
        },
        "ios": {
          "2019-07": "n"
        },
        "android": {
          "2019-07": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n"
        },
        "ios": {
          "2020-03": "n"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "a #2",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Only supported through a `<link>` tag.",
      "2": "Partial. Only supported directly through a `<style>` tag.",
      "3": "Buggy. Support depends on the version of IE installed.",
      "4": "Partial. The declaration is supported but distant fonts are ignored.",
      "5": "Buggy. Elements using a font declared with `@font-face` ignore the font stack and fall back to Times New Roman. Use `mso-generic-font-family` and `mso-font-alt` to control the fallback.",
      "6": "Not supported. Roboto and Google Sans can be used, but only because they're embedded with the webmail's own styles.",
      "7": "Not supported. The `@font-face` declaration is kept but the `src` property is removed.",
      "8": "Not supported when using a Microsoft email address; outlook, live, hotmail, etc."
    },
    "notes": null
  },
  "@import": {
    "slug": "css-at-import",
    "description": "This is the description of the `@import` property.",
    "url": "https://www.caniemail.com/features/css-at-import/",
    "last_test_date": "2019-02-28",
    "stats": {
      "apple-mail": {
        "macos": {
          "12.4": "y"
        },
        "ios": {
          "12.1": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2019-02": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2019-02": "n"
        },
        "mobile-webmail": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-08": "n",
          "2021-03": "n"
        },
        "ios": {
          "2019-08": "y",
          "2023-12": "n"
        },
        "android": {
          "2019-08": "y",
          "2023-12": "n"
        }
      },
      "outlook": {
        "windows": {
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2019-02": "y"
        },
        "macos": {
          "2019-02": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2019-02": "n",
          "2023-12": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2019-02": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.8": "y",
          "78.5": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2019-02": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2019-02": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2019-02": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2020-01": "n"
        }
      },
      "samsung-email": {
        "android": {
          "5.0.10.2": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-08": "n",
          "2025-07": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n"
        },
        "ios": {
          "2020-03": "n"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "n",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "n"
        }
      },
      "wp-pl": {
        "desktop-webmail": {
          "2023-12": "n"
        }
      }
    },
    "notes_by_num": null,
    "notes": null
  },
  "@keyframes": {
    "slug": "css-at-keyframes",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-keyframes/",
    "last_test_date": "2021-05-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        },
        "mobile-webmail": {
          "2021-05": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2021-05": "n #1"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2021-05": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.1": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2021-05": "a #1",
          "2025-07": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "78.10": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2021-05": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "a #1",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "a #2"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Not supported. The `@keyframes` declaration is kept but values are incorrectly prefixed.",
      "2": "Partial. Only supports from and to keyframes. Does not support % keyframes"
    },
    "notes": null
  },
  "@media (-webkit-device-pixel-ratio)": {
    "slug": "css-at-media-device-pixel-ratio",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-media-device-pixel-ratio/",
    "last_test_date": "2019-08-20",
    "stats": {
      "apple-mail": {
        "macos": {
          "10.3": "y"
        },
        "ios": {
          "10.3": "y",
          "12.2": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2019-08": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        },
        "mobile-webmail": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-08": "y #1",
          "2021-03": "y"
        },
        "ios": {
          "2019-08": "y"
        },
        "android": {
          "2019-08": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-01": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2019-08": "y"
        },
        "ios": {
          "2019-08": "y"
        },
        "android": {
          "2019-08": "y"
        }
      },
      "samsung-email": {
        "android": {
          "5.0.10.2": "y",
          "6.0": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-08": "y",
          "2025-07": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.3": "n",
          "78.5": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2019-08": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2019-02": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2019-02": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n"
        },
        "ios": {
          "2020-03": "n"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Buggy. The first rule inside a media query is not prefixed."
    },
    "notes": null
  },
  "@media (hover), @media (any-hover)": {
    "slug": "css-at-media-hover",
    "description": "This media query tests whether the user's input device[s] (i.e mouse, trackpad etc.) can hover over elements",
    "url": "https://www.caniemail.com/features/css-at-media-hover/",
    "last_test_date": "2022-08-29",
    "stats": {
      "apple-mail": {
        "macos": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "n"
        },
        "android": {
          "2022-08": "n"
        },
        "mobile-webmail": {
          "2022-08": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2022-08": "u"
        },
        "ios": {
          "2022-08": "u"
        },
        "android": {
          "2022-08": "u"
        }
      },
      "outlook": {
        "windows": {
          "2022-08": "n"
        },
        "windows-mail": {
          "2022-08": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "samsung-email": {
        "android": {
          "10": "y",
          "11": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2024-03": "y",
          "2025-07": "n"
        },
        "ios": {
          "2024-03": "n"
        },
        "android": {
          "2024-03": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "2022-08": "u"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "n"
        },
        "android": {
          "2022-08": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "n"
        },
        "android": {
          "2022-08": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2022-08": "u"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2022-08": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2022-08": "u"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2022-08": "u",
          "2025-07": "n"
        }
      }
    },
    "notes_by_num": null,
    "notes": null
  },
  "@media (orientation)": {
    "slug": "css-at-media-orientation",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-media-orientation/",
    "last_test_date": "2019-08-20",
    "stats": {
      "apple-mail": {
        "macos": {
          "10.3": "y"
        },
        "ios": {
          "12": "y",
          "13": "y",
          "15": "y",
          "10.3": "n",
          "18.3.2": "a #2"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2019-08": "y"
        },
        "ios": {
          "2019-08": "y",
          "2025-04": "n"
        },
        "android": {
          "2019-08": "y"
        },
        "mobile-webmail": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-08": "y #1",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2019-08": "n",
          "2024-04": "y"
        },
        "android": {
          "2019-08": "y",
          "2024-04": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-01": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2019-08": "y"
        },
        "ios": {
          "2019-08": "y"
        },
        "android": {
          "2019-08": "y"
        }
      },
      "samsung-email": {
        "android": {
          "5.0.10.2": "n",
          "6.0": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-08": "y",
          "2025-07": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.3": "y",
          "78.5": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2019-08": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2019-02": "n"
        },
        "ios": {
          "2019-02": "n"
        },
        "android": {
          "2019-02": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n"
        },
        "ios": {
          "2020-03": "n"
        },
        "android": {
          "2020-03": "n"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Buggy. The first rule inside a media query is not prefixed.",
      "2": "Partial. `orientation:portrait` is not supported."
    },
    "notes": null
  },
  "@media (prefers-color-scheme)": {
    "slug": "css-at-media-prefers-color-scheme",
    "description": "This media query allows to theme for system light and dark mode.",
    "url": "https://www.caniemail.com/features/css-at-media-prefers-color-scheme/",
    "last_test_date": "2023-03-08",
    "stats": {
      "apple-mail": {
        "macos": {
          "10.3": "n",
          "12.4": "y",
          "16.0": "y"
        },
        "ios": {
          "12.2": "n",
          "13.0": "y",
          "16.1": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-01": "n",
          "2022-12": "n"
        },
        "ios": {
          "2020-01": "n",
          "2022-12": "n"
        },
        "android": {
          "2020-01": "n",
          "2022-12": "n"
        },
        "mobile-webmail": {
          "2020-02": "n",
          "2022-12": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-08": "y",
          "2021-03": "y",
          "2022-12": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-01": "n",
          "2022-12": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-01": "n",
          "2022-12": "n",
          "2024-04": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-01": "n"
        },
        "macos": {
          "2019": "y",
          "16.70": "y #3",
          "16.80": "y #3"
        },
        "outlook-com": {
          "2019-07": "y",
          "2022-12": "y #3"
        },
        "ios": {
          "2020-01": "y",
          "2022-12": "y #3"
        },
        "android": {
          "2020-01": "n",
          "2022-12": "n #3",
          "2023-03": "y #3"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "n",
          "6.1": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-08": "y",
          "2022-12": "y",
          "2025-07": "n"
        },
        "ios": {
          "2019-08": "n",
          "2022-12": "n"
        },
        "android": {
          "2019-08": "n",
          "2022-12": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.8": "n",
          "68.4": "y",
          "78.5": "n",
          "91.13": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-01": "n #1"
        },
        "ios": {
          "2020-01": "n #1"
        },
        "android": {
          "2020-01": "n #1"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-01": "n #1",
          "2022-12": "n #6"
        },
        "ios": {
          "2020-01": "n #1",
          "2022-12": "n"
        },
        "android": {
          "2020-01": "n #1",
          "2022-12": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n",
          "2022-12": "n"
        },
        "ios": {
          "2020-03": "n"
        },
        "android": {
          "2020-03": "n"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y",
          "2022-12": "n #5"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "n",
          "2022-12": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n #2",
          "2022-12": "y #4"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2022-12": "y",
          "2025-07": "n"
        }
      },
      "free-fr": {
        "desktop-webmail": {
          "2022-12": "y"
        }
      },
      "t-online-de": {
        "desktop-webmail": {
          "2022-12": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Not supported. `@media (prefers-color-scheme)` is transformed into `@media ( _filtered_a )`.",
      "2": "Not supported. `@media (prefers-color-scheme:dark)` is transformed into `@media none`.",
      "3": "Additional custom `data` attributes (`data-ogsc`, `data-ogac`, `data-ogsb`, `data-ogab`) are added when viewing an email in dark mode. See [this article](https://www.hteumeuleu.com/2021/emails-react-outlook-com-dark-mode/) for examples.",
      "4": "`@media (prefers-color-scheme:dark)` is transformed into `@media all` at run time if it applies.",
      "5": "Not supported. `@media (prefers-color-scheme:dark)` is transformed into `@media (false)`",
      "6": "Not supported. `@media (prefers-color-scheme:dark)` is transformed into `@media ()`"
    },
    "notes": null
  },
  "@media (prefers-reduced-motion)": {
    "slug": "css-at-media-prefers-reduced-motion",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-media-prefers-reduced-motion/",
    "last_test_date": "2021-02-20",
    "stats": {
      "apple-mail": {
        "macos": {
          "11": "y",
          "12": "y",
          "13": "y"
        },
        "ios": {
          "11": "y",
          "12": "y",
          "13": "y",
          "14": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-12": "n"
        },
        "ios": {
          "2020-12": "n"
        },
        "android": {
          "2020-12": "n"
        },
        "mobile-webmail": {
          "2020-12": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2021-02": "y",
          "2021-03": "y"
        },
        "ios": {
          "2021-02": "y"
        },
        "android": {
          "2021-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "16005.13426.20316.0": "n"
        },
        "macos": {
          "2020-12": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-12": "y"
        },
        "ios": {
          "2020-12": "y"
        },
        "android": {
          "4.2048.4": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-12": "n"
        },
        "ios": {
          "2021-02": "n"
        },
        "android": {
          "6.16.2.1519779": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-12": "n"
        },
        "ios": {
          "2021-02": "n"
        },
        "android": {
          "2021-02": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.1.31.2": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2021-02": "y"
        },
        "ios": {
          "2021-02": "n"
        },
        "android": {
          "2021-02": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "78.7": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2021-02": "a #2"
        },
        "ios": {
          "2021-02": "a #2"
        },
        "android": {
          "2021-02": "a #2"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2021-02": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2021-02": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n #1"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Not supported. `@media (prefers-reduced-motion:reduce)` is transformed into `@media none`.",
      "2": "Partially supported. Not supported on `picture`."
    },
    "notes": null
  },
  "@media": {
    "slug": "css-at-media",
    "description": "",
    "url": "https://www.caniemail.com/features/css-at-media/",
    "last_test_date": "2023-12-13",
    "stats": {
      "apple-mail": {
        "macos": {
          "10.3": "y"
        },
        "ios": {
          "10.3": "y",
          "12.2": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2019-08": "a #1 #7",
          "2020-01": "a #7"
        },
        "ios": {
          "2019-08": "a #1 #6 #7",
          "2020-01": "a #6 #7"
        },
        "android": {
          "2019-08": "a #1 #6 #7",
          "2022-07": "a #6 #7"
        },
        "mobile-webmail": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2019-08": "y #5",
          "2021-03": "y"
        },
        "ios": {
          "2019-08": "y"
        },
        "android": {
          "2019-08": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "a #1",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-01": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "a #1 #10"
        },
        "outlook-com": {
          "2019-08": "a #1",
          "2023-12": "a #1 #10"
        },
        "ios": {
          "2019-08": "a #1"
        },
        "android": {
          "2019-08": "a #1"
        }
      },
      "samsung-email": {
        "android": {
          "5.0.10.2": "y",
          "6.0": "y",
          "6.1.90.16": "a #9"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2019-08": "y",
          "2025-07": "n"
        },
        "ios": {
          "2019-08": "n"
        },
        "android": {
          "2019-08": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "60.3": "y",
          "78.5": "n",
          "102.11": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2019-08": "a #1 #2",
          "2020-01": "a #2"
        },
        "ios": {
          "2019-08": "a #1 #2",
          "2020-01": "a #2"
        },
        "android": {
          "2019-08": "a #1 #2 #3",
          "2020-01": "a #2 #3",
          "2025-06": "a #2"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2019-02": "a #1 #2",
          "2020-01": "a #2"
        },
        "ios": {
          "2019-02": "a #1 #2",
          "2020-01": "a #2"
        },
        "android": {
          "2019-02": "a #1 #2",
          "2020-01": "a #2"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "n",
          "2023-05": "a #8"
        },
        "ios": {
          "2020-03": "n",
          "2023-05": "a #8"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "a #1 #7"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "y #1"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "y #1"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Does not support nested media queries.",
      "2": "Partial. Only supports `screen`, `min-width`, `max-width`, `min-height` and `max-height` based media queries.",
      "3": "Buggy. Requires a double `<head>` hack to work.",
      "4": "Partial. Does not support simple `@media {}` declarations.",
      "5": "Buggy. The first rule inside a media query is not prefixed.",
      "6": "Partial. Not supported with non Google accounts.",
      "7": "Partial. Does not support height based media queries.",
      "8": "Partial. Does not support landscape media query.",
      "9": "Partial. Not supported with Hotmail/Outlook accounts.",
      "10": "Partial. Nested media queries are removed."
    },
    "notes": null
  },
  "@supports": {
    "slug": "css-at-supports",
    "description": null,
    "url": "https://www.caniemail.com/features/css-at-supports/",
    "last_test_date": "2020-05-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-05": "n"
        },
        "ios": {
          "2020-05": "n"
        },
        "android": {
          "2020-05": "n"
        },
        "mobile-webmail": {
          "2020-05": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-05": "y",
          "2021-03": "y"
        },
        "ios": {
          "2020-05": "y"
        },
        "android": {
          "2020-05": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-05": "n"
        },
        "macos": {
          "2011": "y",
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2020-05": "n"
        },
        "ios": {
          "2020-05": "n"
        },
        "android": {
          "2020-05": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-05": "y",
          "2025-07": "n"
        },
        "ios": {
          "2020-05": "n"
        },
        "android": {
          "2020-05": "n"
        }
      },
      "thunderbird": {
        "macos": {
          "68.7": "y",
          "78.5": "n"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-05": "y #1"
        },
        "ios": {
          "2020-05": "y #1"
        },
        "android": {
          "2020-05": "y #1"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-05": "y #1"
        },
        "ios": {
          "2020-05": "y #1"
        },
        "android": {
          "2020-05": "y #1"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-05": "n"
        },
        "ios": {
          "2020-05": "n"
        },
        "android": {
          "2020-05": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "n"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n #2"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y",
          "2025-07": "n"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Properties not supported by the client are replaced by `_filtered_a` inside the parenthesis.",
      "2": "Not supported. `@supports` is transformed into `@media not all`."
    },
    "notes": null
  }
} as const;
