// This file is auto-generated by src/scripts/can-i-email.js
// Do not edit this file manually.

export const canIEmailCSSFunctions = {
  "clamp()": {
    "slug": "css-function-clamp",
    "description": "Support for the CSS `clamp()` function.",
    "url": "https://www.caniemail.com/features/css-function-clamp/",
    "last_test_date": "2021-05-07",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "n",
          "14.0": "y"
        },
        "ios": {
          "13": "n",
          "14.5": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "a #1"
        },
        "android": {
          "2021-05": "a #1"
        },
        "mobile-webmail": {
          "2021-05": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2021-05": "n"
        },
        "macos": {
          "2011": "n",
          "2016": "n",
          "16.80": "n"
        },
        "outlook-com": {
          "2021-05": "n",
          "2023-12": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "n",
          "6.2.06.0": "a #2"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "thunderbird": {
        "macos": {
          "78.10": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Not supported with non Google accounts.",
      "2": "Partial. Not supported with Microsoft accounts."
    },
    "notes": null
  },
  "light-dark()": {
    "slug": "css-function-light-dark",
    "description": "Enables setting two colors (one for light and the other for dark mode) for a property.",
    "url": "https://www.caniemail.com/features/css-function-light-dark/",
    "last_test_date": "2024-08-14",
    "stats": {
      "apple-mail": {
        "macos": {
          "16.0": "y #1"
        },
        "ios": {
          "17.5.1": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2024-08": "n"
        },
        "ios": {
          "2024-08": "n"
        },
        "android": {
          "2024-08": "n"
        },
        "mobile-webmail": {
          "2024-08": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2024-08": "n"
        },
        "ios": {
          "2024-08": "n"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "outlook": {
        "windows": {
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2024-08": "n"
        },
        "macos": {
          "16.88": "n"
        },
        "outlook-com": {
          "2024-08": "n"
        },
        "ios": {
          "2024-08": "n"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "samsung-email": {
        "android": {
          "6.2": "a #3"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2024-08": "a #2"
        },
        "ios": {
          "2024-08": "a #1 #2"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "thunderbird": {
        "macos": {
          "115.10.1": "n",
          "128.1.0": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2024-08": "n"
        },
        "ios": {
          "2024-08": "n"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2024-08": "n"
        },
        "ios": {
          "2024-08": "n"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2024-08": "a #2"
        },
        "ios": {
          "2024-08": "y #1"
        },
        "android": {
          "2024-08": "u"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2024-08": "a #2"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2024-08": "a #2"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2024-08": "u"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2024-08": "a #2"
        }
      },
      "free-fr": {
        "desktop-webmail": {
          "2024-08": "n"
        }
      },
      "t-online-de": {
        "desktop-webmail": {
          "2024-08": "a #2"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2024-08": "n"
        }
      }
    },
    "notes_by_num": {
      "1": "Only supported if you’ve updated your OS with Safari 17.5 or later.",
      "2": "Buggy. The function is supported but the color stays light even in dark mode.",
      "3": "Partial. Not supported with Hotmail/Outlook accounts."
    },
    "notes": null
  },
  "max()": {
    "slug": "css-function-max",
    "description": "Support for the CSS `max()` function.",
    "url": "https://www.caniemail.com/features/css-function-max/",
    "last_test_date": "2021-05-07",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y",
          "14.0": "y"
        },
        "ios": {
          "13": "y",
          "14.5": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "a #1"
        },
        "android": {
          "2021-05": "a #1"
        },
        "mobile-webmail": {
          "2021-05": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2021-05": "n"
        },
        "macos": {
          "2011": "n",
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2021-05": "n",
          "2023-12": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "n",
          "6.2.06.0": "a #2"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "thunderbird": {
        "macos": {
          "78.10": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Not supported with non Google accounts.",
      "2": "Partial. Not supported with Microsoft accounts."
    },
    "notes": null
  },
  "min()": {
    "slug": "css-function-min",
    "description": "Support for the CSS `min()` function.",
    "url": "https://www.caniemail.com/features/css-function-min/",
    "last_test_date": "2021-05-07",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y",
          "14.0": "y"
        },
        "ios": {
          "13": "y",
          "14.5": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "a #1"
        },
        "android": {
          "2021-05": "a #1"
        },
        "mobile-webmail": {
          "2021-05": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2021-05": "n"
        },
        "macos": {
          "2011": "n",
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2021-05": "n",
          "2023-12": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "samsung-email": {
        "android": {
          "6.0": "n",
          "6.2.06.0": "a #2"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "thunderbird": {
        "macos": {
          "78.10": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2021-05": "n"
        },
        "ios": {
          "2021-05": "n"
        },
        "android": {
          "2021-05": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2021-05": "y"
        },
        "ios": {
          "2021-05": "y"
        },
        "android": {
          "2021-05": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2021-05": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-06": "n"
        },
        "ios": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-06": "y"
        },
        "android": {
          "2022-06": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Not supported with non Google accounts.",
      "2": "Partial. Not supported with Microsoft accounts."
    },
    "notes": null
  }
} as const;
