// This file is auto-generated by src/scripts/can-i-email.js
// Do not edit this file manually.

export const canIEmailCSSUnits = {
  "CSS calc() function": {
    "slug": "css-unit-calc",
    "description": "Support for CSS calc function.",
    "url": "https://www.caniemail.com/features/css-unit-calc/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "a #1"
        },
        "android": {
          "2020-02": "a #1"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "n"
        },
        "outlook-com": {
          "2020-02": "n",
          "2024-01": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Not supported with non Google accounts."
    },
    "notes": ""
  },
  "ch unit": {
    "slug": "css-unit-ch",
    "description": "Support for ch unit, relative to the width of a '0'.",
    "url": "https://www.caniemail.com/features/css-unit-ch/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "cm unit": {
    "slug": "css-unit-cm",
    "description": "Support for centimeters unit",
    "url": "https://www.caniemail.com/features/css-unit-cm/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "em unit": {
    "slug": "css-unit-em",
    "description": "Support for em unit, relative to the current font-size.",
    "url": "https://www.caniemail.com/features/css-unit-em/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "ex unit": {
    "slug": "css-unit-ex",
    "description": "Support for ex unit, relative to the height of an 'x'.",
    "url": "https://www.caniemail.com/features/css-unit-ex/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "in unit": {
    "slug": "css-unit-in",
    "description": "Support for inches unit",
    "url": "https://www.caniemail.com/features/css-unit-in/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "initial unit": {
    "slug": "css-unit-initial",
    "description": "Support for initial keyword value.",
    "url": "https://www.caniemail.com/features/css-unit-initial/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "a #1"
        },
        "ios": {
          "2020-02": "a #2"
        },
        "android": {
          "2020-02": "a #2"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "a #1",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Partial. Webmail rendering doesn't work in IE.",
      "2": "Partial. Not supported with non Google accounts."
    },
    "notes": ""
  },
  "mm unit": {
    "slug": "css-unit-mm",
    "description": "Support for millimeters unit",
    "url": "https://www.caniemail.com/features/css-unit-mm/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "pc unit": {
    "slug": "css-unit-pc",
    "description": "Support for picas unit",
    "url": "https://www.caniemail.com/features/css-unit-pc/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "% unit": {
    "slug": "css-unit-percent",
    "description": "Support for percentage unit",
    "url": "https://www.caniemail.com/features/css-unit-percent/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "pt unit": {
    "slug": "css-unit-pt",
    "description": "Support for points unit",
    "url": "https://www.caniemail.com/features/css-unit-pt/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y",
          "2021-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "px unit": {
    "slug": "css-unit-px",
    "description": "Support for pixels unit",
    "url": "https://www.caniemail.com/features/css-unit-px/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "y",
          "2007": "y",
          "2010": "y",
          "2013": "y",
          "2016": "y",
          "2019": "y"
        },
        "windows-mail": {
          "2020-02": "y"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "y",
          "2024-04": "y"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "y"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "y"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "rem unit": {
    "slug": "css-unit-rem",
    "description": "Support for rem unit, relative to the root font-size.",
    "url": "https://www.caniemail.com/features/css-unit-rem/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {},
    "notes": ""
  },
  "vh unit": {
    "slug": "css-unit-vh",
    "description": "Support for viewport height unit.",
    "url": "https://www.caniemail.com/features/css-unit-vh/",
    "last_test_date": "2023-10-01",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y",
          "15": "a #2",
          "17": "a #2"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y #1"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Buggy. Can affect the preview window size, meaning content can get lost.",
      "2": "Buggy. Value resolves to zero"
    },
    "notes": ""
  },
  "vmax unit": {
    "slug": "css-unit-vmax",
    "description": "Support for viewport maximum unit.",
    "url": "https://www.caniemail.com/features/css-unit-vmax/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y #1"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Buggy. VH values can affect the preview window size, meaning content can get lost.",
      "2": "Buggy. VH values resolves to zero"
    },
    "notes": ""
  },
  "vmin unit": {
    "slug": "css-unit-vmin",
    "description": "Support for viewport minimum unit.",
    "url": "https://www.caniemail.com/features/css-unit-vmin/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y",
          "2024-01": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "n"
        },
        "ios": {
          "2020-02": "n"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "n"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "y"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "a #2"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y #1"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "Buggy. VH values can affect the preview window size, meaning content can get lost.",
      "2": "Buggy. VH values resolves to zero"
    },
    "notes": ""
  },
  "vw unit": {
    "slug": "css-unit-vw",
    "description": "Support for viewport width unit.",
    "url": "https://www.caniemail.com/features/css-unit-vw/",
    "last_test_date": "2020-02-25",
    "stats": {
      "apple-mail": {
        "macos": {
          "13": "y"
        },
        "ios": {
          "13": "y"
        }
      },
      "gmail": {
        "desktop-webmail": {
          "2020-02": "y #1"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        },
        "mobile-webmail": {
          "2020-02": "y"
        }
      },
      "outlook": {
        "windows": {
          "2003": "n",
          "2007": "n",
          "2010": "n",
          "2013": "n",
          "2016": "n",
          "2019": "n"
        },
        "windows-mail": {
          "2020-02": "n"
        },
        "macos": {
          "2016": "y",
          "16.80": "y"
        },
        "outlook-com": {
          "2020-02": "y #1",
          "2024-01": "y #1"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "samsung-email": {
        "android": {
          "9.0": "y"
        }
      },
      "thunderbird": {
        "windows": {
          "2020-02": "y"
        },
        "macos": {
          "68.4": "y"
        }
      },
      "aol": {
        "desktop-webmail": {
          "2020-02": "y #1"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "yahoo": {
        "desktop-webmail": {
          "2020-02": "y #1"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "orange": {
        "desktop-webmail": {
          "2020-02": "y",
          "2021-03": "n",
          "2024-04": "n"
        },
        "ios": {
          "2020-02": "y",
          "2024-04": "n"
        },
        "android": {
          "2020-02": "y",
          "2024-04": "n"
        }
      },
      "sfr": {
        "desktop-webmail": {
          "2020-02": "y"
        },
        "ios": {
          "2020-02": "y"
        },
        "android": {
          "2020-02": "y"
        }
      },
      "protonmail": {
        "desktop-webmail": {
          "2020-03": "y"
        },
        "ios": {
          "2020-03": "y"
        },
        "android": {
          "2020-03": "y"
        }
      },
      "hey": {
        "desktop-webmail": {
          "2020-06": "y"
        }
      },
      "mail-ru": {
        "desktop-webmail": {
          "2020-10": "y #1"
        }
      },
      "fastmail": {
        "desktop-webmail": {
          "2021-07": "n"
        }
      },
      "laposte": {
        "desktop-webmail": {
          "2021-08": "y"
        }
      },
      "gmx": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "web-de": {
        "desktop-webmail": {
          "2022-08": "n"
        },
        "ios": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      },
      "ionos-1and1": {
        "desktop-webmail": {
          "2022-08": "y"
        },
        "android": {
          "2022-08": "y"
        }
      }
    },
    "notes_by_num": {
      "1": "The HTML of the email message is embedded directly on the webmail (not in an <iframe>) and may not fill the full viewport's width. In this case, the vw values are relevant to the viewport (browser window) not the email message."
    },
    "notes": ""
  }
} as const;
