import fs from "node:fs/promises";
import path from "node:path";
import { propsToType } from "./__generated_maps__/props-to-type";
import SHORTHANDS from "../css/short-hands";
import { camelToKebab } from "../utils/camel-to-kebab";
import type { CanIEmailItem, ProcessedItem } from "./types";
import { extractNeededFields } from "./extract-needed-fields";

export class CanIEmailMapsBuilder {
  private cssUnits: Record<string, ProcessedItem> = {};
  private cssFunctions: Record<string, ProcessedItem> = {};
  private cssAtRules: Record<string, ProcessedItem> = {};
  private cssValues: Record<string, ProcessedItem> = {};
  private cssProps: Record<string, ProcessedItem> = {};

  processItems(items: CanIEmailItem[]): this {
    for (const item of items) {
      if (item.category !== "css") continue;
      this.processItem(item);
    }
    return this;
  }

  private isUnit(slug: string): boolean {
    return slug.startsWith("css-unit-") && slug !== "css-unit-calc";
  }

  private isFunction(slug: string, title: string): boolean {
    return (
      slug.startsWith("css-function-") ||
      slug === "css-unit-calc" ||
      slug === "css-linear-gradient" ||
      title.endsWith("()")
    );
  }

  private isPseudo(slug: string): boolean {
    return slug.includes("-pseudo-");
  }

  private isAtRule(title: string): boolean {
    return title.startsWith("@");
  }

  private isValue(title: string, isPseudo: boolean): boolean {
    return title.includes(":") && !isPseudo;
  }

  private processItem(item: CanIEmailItem): void {
    const title = item.title.trim();
    const slug = item.slug;

    const isUnit = this.isUnit(slug);
    const isFunction = this.isFunction(slug, title);
    const isPseudo = this.isPseudo(slug);
    const isAtRule = this.isAtRule(title);
    const isValue = this.isValue(title, isPseudo);

    let cleanTitle = title;
    if (isUnit) {
      cleanTitle = title.replace(/\sunit$/i, "").trim();
    }
    if (isFunction) {
      const match = title.match(/([a-z-]+)\(\)/i);
      if (match) {
        cleanTitle = `${match[1]}()`;
      }
    }
    if (isValue) {
      cleanTitle = title.replace(/\s*:\s*/, ":").trim();
    }

    if (
      !isUnit &&
      !isFunction &&
      !isAtRule &&
      !isPseudo &&
      !isValue &&
      cleanTitle.includes(" ") &&
      !cleanTitle.includes("&")
    ) {
      return;
    }

    if (isUnit) {
      this.cssUnits[cleanTitle] = extractNeededFields(item, cleanTitle);
    } else if (isFunction) {
      this.cssFunctions[cleanTitle] = extractNeededFields(item, cleanTitle);
    } else if (isAtRule) {
      this.cssAtRules[cleanTitle] = extractNeededFields(item, cleanTitle);
    } else if (isValue) {
      this.cssValues[cleanTitle] = extractNeededFields(item, cleanTitle);
    } else if (cleanTitle.includes("&")) {
      const parts = cleanTitle.split("&").map((s) => s.trim());
      for (const part of parts) {
        if (!part.includes(" ")) {
          this.cssProps[part] = extractNeededFields(item, part);
        }
      }
    } else if (!isPseudo) {
      this.cssProps[cleanTitle] = extractNeededFields(item, cleanTitle);
    }
  }

  supplementMissingProperties(): this {
    for (const prop in propsToType) {
      if (!this.cssProps[prop]) {
        const camelProp = prop.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
        const longhandCamel = SHORTHANDS[camelProp];

        let baseData = undefined;
        if (longhandCamel) {
          const longhandKebab = camelToKebab(longhandCamel);
          baseData = this.cssProps[longhandKebab];
        }

        if (baseData) {
          this.cssProps[prop] = {
            ...baseData,
            type: propsToType[prop],
          };
        } else {
          this.cssProps[prop] = {
            slug: "<could-not-find-can-i-email-entry>",
            description: null,
            url: "<could-not-find-can-i-email-entry>",
            last_test_date: "<could-not-find-can-i-email-entry>",
            coverage: {
              support: 100,
              partial: 0,
              notSupported: 0,
            },
            notes: null,
            type: propsToType[prop],
          };
        }
      }
    }
    return this;
  }

  async saveTo(mapsDir: string): Promise<void> {
    await fs.mkdir(mapsDir, { recursive: true });

    const files = {
      "properties.ts": { name: "canIEmailCSSProperties", data: this.cssProps },
      "units.ts": { name: "canIEmailCSSUnits", data: this.cssUnits },
      "functions.ts": { name: "canIEmailCSSFunctions", data: this.cssFunctions },
      "at-rules.ts": { name: "canIEmailCSSAtRules", data: this.cssAtRules },
      "values.ts": { name: "canIEmailCSSValues", data: this.cssValues },
    };

    for (const [filename, { name, data }] of Object.entries(files)) {
      const filePath = path.join(mapsDir, filename);
      const content = `// This file is auto-generated by src/can-i-email/index.ts
// Do not edit this file manually.
import type { ProcessedItem } from "../types";

export const ${name}: Record<string, ProcessedItem> = ${JSON.stringify(data, null, 2)};
`;
      await fs.writeFile(filePath, content, "utf8");
      console.log(`Saved ${filename} to ${mapsDir}`);
    }
  }
}
